name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  us:
    runs-on: ubuntu-latest
    environment: US
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/aws-ddns-us .
            --build-arg AWS_LAMBDA="${{ secrets.AWS_LAMBDA }}"


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/aws-ddns-us

  cn:
    runs-on: ubuntu-latest
    environment: CN
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/aws-ddns-cn .
            --build-arg AWS_LAMBDA="${{ secrets.AWS_LAMBDA }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker
        run: docker push qinbatista/aws-ddns-cn