name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  us:
    runs-on: ubuntu-latest
    environment: US
    steps:
      - uses: actions/checkout@v3

      # ----- Docker Hub login -----
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ----- QEMU for cross-arch builds -----
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      # ----- Buildx builder -----
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ----- Build & push multi-arch image -----
      - name: Build and push (US)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qinbatista/aws-ddns-us:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            AWS_LAMBDA=${{ secrets.AWS_LAMBDA }}

  cn:
    runs-on: ubuntu-latest
    environment: CN
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (CN)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qinbatista/aws-ddns-cn:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            AWS_LAMBDA=${{ secrets.AWS_LAMBDA }}

  timov4:
    runs-on: ubuntu-latest
    environment: TIMO
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (TIMO)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: qinbatista/aws-ddns-timov4:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            AWS_LAMBDA=${{ secrets.AWS_LAMBDA }}